#include "vfs.h"
#include "../process/process.h"
#include "../fs/rixfs.h"
#include <stddef.h>
#include <stdint.h>

typedef struct { uint8_t used; uint8_t flags; uint16_t reserved; pid_t pid; uint64_t inode; rix_vfs_type_t type; uint64_t offset; } vfs_file_t;
static vfs_file_t files[RIX_PROCESS_MAX][RIX_VFS_FD_MAX];

static int alloc_fd(pid_t pid){rix_process_t*p=process_lookup(pid);if(!p)return-1;for(int fd=3;fd<RIX_VFS_FD_MAX;fd++)if(!(p->fd_bitmap&(1ULL<<fd))){p->fd_bitmap|=1ULL<<fd;files[pid][fd].used=1;files[pid][fd].pid=pid;files[pid][fd].flags=0;files[pid][fd].offset=0;return fd;}return-2;}
static vfs_file_t *get_file(pid_t pid,int fd){if(fd<0||fd>=RIX_VFS_FD_MAX||pid>=RIX_PROCESS_MAX)return (vfs_file_t*)0;if(!files[pid][fd].used)return (vfs_file_t*)0;return &files[pid][fd];}
static int split_parent(const char *path,char *parent,char *name){size_t n=0,last=0;if(!path||path[0]!='/')return-1;while(path[n]){if(path[n]=='/')last=n;n++;if(n>=RIX_VFS_PATH_MAX)return-1;}if(n<=1||last==0){parent[0]='/';parent[1]=0;last=0;}else{if(last>=RIX_VFS_PATH_MAX)return-1;for(size_t i=0;i<last;i++)parent[i]=path[i];parent[last]=0;}size_t start=last?last+1:1,nn=n-start;if(nn==0||nn>RIX_VFS_NAME_MAX)return-1;for(size_t i=0;i<nn;i++)name[i]=path[start+i];name[nn]=0;return 0;}
int vfs_open(uint64_t pid,const char *path,uint32_t flags,uint32_t mode,int *out_fd){if(!out_fd||pid>=RIX_PROCESS_MAX)return-1;rixfs_t*fs=vfs_root_fs();if(!fs)return-2;char norm[RIX_VFS_PATH_MAX];if(vfs_normalize_path(path,norm,sizeof(norm)))return-3;rix_vfs_path_t vp;if(vfs_lookup(norm,&vp)!=0){if(!(flags&RIX_VFS_O_CREAT))return-4;char parent[RIX_VFS_PATH_MAX],name[RIX_VFS_NAME_MAX+1];if(split_parent(norm,parent,name))return-5;rix_vfs_path_t pp;if(vfs_lookup(parent,&pp)||pp.node->type!=RIX_VFS_DIR)return-6;uint64_t ino;if(rixfs_create(fs,pp.node->inode,name,mode,process_lookup(pid)->uid,process_lookup(pid)->gid,&ino))return-7;if(vfs_lookup(norm,&vp))return-8;}else if((flags&RIX_VFS_O_CREAT)&&vp.node->type==RIX_VFS_DIR){return-9;}int fd=alloc_fd(pid);if(fd<0)return-10;files[pid][fd].inode=vp.node->inode;files[pid][fd].type=vp.node->type;files[pid][fd].flags=(uint8_t)flags;if((flags&RIX_VFS_O_TRUNC)&&(flags&(RIX_VFS_O_WRONLY|RIX_VFS_O_RDWR))&&vp.node->type==RIX_VFS_FILE){if(rixfs_truncate(fs,vp.node->inode,0)){vfs_close(pid,fd);return-11;}}*out_fd=fd;return 0;}
int vfs_close(uint64_t pid,int fd){rix_process_t*p=process_lookup(pid);vfs_file_t*f=get_file(pid,fd);if(!p||!f)return-1;p->fd_bitmap&=~(1ULL<<fd);for(size_t i=0;i<sizeof(*f);i++)((uint8_t*)f)[i]=0;return 0;}
int vfs_read(uint64_t pid,int fd,void *buffer,size_t size,size_t *out_read){if(!out_read||(!buffer&&size))return-1;vfs_file_t*f=get_file(pid,fd);rixfs_t*fs=vfs_root_fs();if(!f||!fs||f->type!=RIX_VFS_FILE)return-2;rixfs_inode_disk_t in;if(rixfs_read_inode(fs,f->inode,&in))return-3;if(f->offset>=in.size){*out_read=0;return 0;}uint64_t avail=in.size-f->offset;size_t n=size;if((uint64_t)n>avail)n=(size_t)avail;if(rixfs_read(fs,f->inode,f->offset,buffer,n))return-4;f->offset+=n;*out_read=n;return 0;}
int vfs_write(uint64_t pid,int fd,const void *buffer,size_t size,size_t *out_written){if(!out_written||(!buffer&&size))return-1;vfs_file_t*f=get_file(pid,fd);rixfs_t*fs=vfs_root_fs();if(!f||!fs||f->type!=RIX_VFS_FILE)return-2;if(!(f->flags&(RIX_VFS_O_WRONLY|RIX_VFS_O_RDWR)))return-3;if(f->offset>UINT64_MAX-(uint64_t)size)return-4;uint64_t end=f->offset+(uint64_t)size;rixfs_inode_disk_t in;if(rixfs_read_inode(fs,f->inode,&in))return-5;if(end>in.size&&rixfs_truncate(fs,f->inode,end))return-6;if(rixfs_write(fs,f->inode,f->offset,buffer,size))return-7;f->offset=end;*out_written=size;return 0;}
int vfs_readdir(uint64_t pid,int fd,uint64_t *offset,rix_vfs_dirent_t*out,char*name,size_t cap){if(!offset||!out||!name)return-1;vfs_file_t*f=get_file(pid,fd);rixfs_t*fs=vfs_root_fs();if(!f||!fs||f->type!=RIX_VFS_DIR)return-2;rixfs_dirent_disk_t e;if(rixfs_readdir(fs,f->inode,offset,&e,name,cap)!=0)return-3;out->inode=e.inode;out->type=e.type;return 0;}
int vfs_stat(const char*path,rix_vnode_t*out){if(!out)return-1;rix_vfs_path_t p;if(vfs_lookup(path,&p))return-2;*out=*p.node;return 0;}
int vfs_mkdir(const char*path,uint32_t mode,uint32_t uid,uint32_t gid){rixfs_t*fs=vfs_root_fs();if(!fs)return-1;char norm[RIX_VFS_PATH_MAX],parent[RIX_VFS_PATH_MAX],name[RIX_VFS_NAME_MAX+1];if(vfs_normalize_path(path,norm,sizeof(norm))||split_parent(norm,parent,name))return-2;rix_vfs_path_t pp;if(vfs_lookup(parent,&pp)||pp.node->type!=RIX_VFS_DIR)return-3;uint64_t ino;return rixfs_mkdir(fs,pp.node->inode,name,mode,uid,gid,&ino);}
int vfs_unlink(const char*path){rixfs_t*fs=vfs_root_fs();if(!fs)return-1;char norm[RIX_VFS_PATH_MAX],parent[RIX_VFS_PATH_MAX],name[RIX_VFS_NAME_MAX+1];if(vfs_normalize_path(path,norm,sizeof(norm))||split_parent(norm,parent,name))return-2;rix_vfs_path_t pp;if(vfs_lookup(parent,&pp)||pp.node->type!=RIX_VFS_DIR)return-3;return rixfs_unlink(fs,pp.node->inode,name);}
