#include "rixfs.h"
#include "rixfs_dir.h"
#include "../mm/pmm.h"
#include <stddef.h>
#include <stdint.h>

static int rd(rix_block_device_t *d,uint64_t s,void *b){rix_bio_t x={0};x.op=RIX_BIO_READ;x.sector=s;x.count=1;x.buffer=b;x.buffer_size=d->sector_size;return block_submit(d,&x);}
static int wr(rix_block_device_t *d,uint64_t s,const void *b){rix_bio_t x={0};x.op=RIX_BIO_WRITE;x.sector=s;x.count=1;x.buffer=(void*)b;x.buffer_size=d->sector_size;return block_submit(d,&x);}
static uint64_t hash64(const void *p,size_t n){const uint8_t *b=p;uint64_t h=1469598103934665603ULL;for(size_t i=0;i<n;i++)h=(h^b[i])*1099511628211ULL;return h;}
static int inode_pos(const rixfs_t *f,uint64_t ino,uint64_t *s,uint32_t *o){if(!f||!f->mounted||!ino||ino>f->super.inode_count)return -1;uint64_t x=(ino-1)*RIXFS_INODE_SIZE;*s=f->super.inode_table_sector+x/f->device->sector_size;*o=(uint32_t)(x%f->device->sector_size);return *o+RIXFS_INODE_SIZE<=f->device->sector_size?0:-2;}
int rixfs_write_inode(rixfs_t *f,uint64_t ino,const rixfs_inode_disk_t *in){uint64_t s;uint32_t o;if(!in||inode_pos(f,ino,&s,&o))return -1;uint64_t q=pmm_alloc_page();if(!q)return -2;uint8_t *b=(uint8_t*)(uintptr_t)q;int r=rd(f->device,s,b);if(!r){for(size_t i=0;i<sizeof(*in);i++)b[o+i]=((const uint8_t*)in)[i];r=wr(f->device,s,b);}pmm_free_page(q);return r;}
static int bit(rixfs_t *f,uint64_t sec,int set){if(!f||!f->mounted||sec>=f->super.total_sectors)return -1;uint64_t bs=f->device->sector_size,x=sec/8,bsec=f->super.bitmap_sector+x/bs,off=x%bs;if(bsec>=f->super.bitmap_sector+f->super.bitmap_sectors)return -2;uint64_t q=pmm_alloc_page();if(!q)return -3;uint8_t *b=(uint8_t*)(uintptr_t)q;int r=rd(f->device,bsec,b);if(!r){uint8_t m=(uint8_t)(1u<<(sec%8));if(set)b[off]|=m;else b[off]&=(uint8_t)~m;r=wr(f->device,bsec,b);}pmm_free_page(q);return r;}
static int bit_get(rixfs_t *f,uint64_t sec,int *used){uint64_t bs=f->device->sector_size,x=sec/8,bsec=f->super.bitmap_sector+x/bs,off=x%bs;if(bsec>=f->super.bitmap_sector+f->super.bitmap_sectors)return -1;uint64_t q=pmm_alloc_page();if(!q)return -2;uint8_t *b=(uint8_t*)(uintptr_t)q;int r=rd(f->device,bsec,b);if(!r)*used=(b[off]&(1u<<(sec%8)))!=0;pmm_free_page(q);return r;}
static int alloc_sec(rixfs_t *f,uint64_t *out){uint64_t s=f->super.free_hint;if(s<f->super.data_start_sector)s=f->super.data_start_sector;for(unsigned pass=0;pass<2;pass++){uint64_t a=pass?f->super.data_start_sector:s,z=pass?s:f->super.total_sectors;for(;a<z;a++){int used=0;if(bit_get(f,a,&used))return -1;if(!used){if(bit(f,a,1))return -2;f->super.free_hint=a+1;*out=a;return 0;}}}return -3;}
static int free_inode_data(rixfs_t *f,const rixfs_inode_disk_t *in){for(unsigned e=0;e<RIXFS_DIRECT_EXTENTS;e++)for(uint64_t j=0;j<in->extent_length[e];j++)if(bit(f,in->extent_start[e]+j,0))return -1;return 0;}
static int valid_name(const char *n,size_t *len){if(!n||!n[0]||n[0]=='/'||n[0]=='.'&&n[1]=='.'&&n[2]==0)return -1;size_t x=0;while(n[x]){if(n[x]=='/'||++x>RIXFS_NAME_MAX)return -1;}*len=x;return 0;}
static int alloc_inode(rixfs_t *f,uint64_t *out){for(uint64_t i=1;i<=f->super.inode_count;i++){rixfs_inode_disk_t in;if(rixfs_read_inode(f,i,&in))return -1;if(in.inode==0){*out=i;return 0;}}return -2;}
static int append_dirent(rixfs_t *f,rixfs_inode_disk_t *dir,uint64_t ino,uint8_t type,const char *name,size_t nl){uint64_t ss=f->device->sector_size;if(ss>UINT16_MAX||nl>RIXFS_NAME_MAX)return -1;uint64_t sec;if(alloc_sec(f,&sec))return -2;if(!dir->extent_length[0]){dir->extent_start[0]=sec;dir->extent_length[0]=1;}else{uint64_t last=dir->extent_start[0]+dir->extent_length[0];if(sec!=last&&append_extent(dir,sec)){/* keep the allocated sector as a separate extent */if(append_extent(dir,sec)){bit(f,sec,0);return -3;}}}
uint64_t off=dir->size;uint64_t max=RIXFS_DIRECT_EXTENTS*ss;if(off+ss>max){bit(f,sec,0);return -4;}if(off%ss!=0){bit(f,sec,0);return -5;}uint64_t q=pmm_alloc_page();if(!q){bit(f,sec,0);return -6;}uint8_t *b=(uint8_t*)(uintptr_t)q;for(uint32_t i=0;i<ss;i++)b[i]=0;uint16_t rs=(uint16_t)ss;for(unsigned i=0;i<8;i++)b[i]=(uint8_t)(ino>>(8*i));b[8]=(uint8_t)rs;b[9]=(uint8_t)(rs>>8);b[10]=type;b[11]=(uint8_t)nl;for(size_t i=0;i<nl;i++)b[16+i]=name[i];int r=wr(f->device,sec,b);pmm_free_page(q);if(r){bit(f,sec,0);return -7;}dir->size+=ss;return 0;}
int rixfs_truncate(rixfs_t *f,uint64_t ino,uint64_t ns){if(!f||!f->mounted)return -1;rixfs_inode_disk_t in;if(rixfs_read_inode(f,ino,&in))return -2;if((in.mode&RIXFS_IFMT)!=RIXFS_IFREG)return -3;uint64_t ss=f->device->sector_size;if(ns>in.size){uint64_t old=(in.size+ss-1)/ss,neu=(ns+ss-1)/ss;for(uint64_t i=old;i<neu;i++){uint64_t s;if(alloc_sec(f,&s)||append_extent(&in,s)){return -4;}}in.size=ns;return rixfs_write_inode(f,ino,&in);}uint64_t keep=(ns+ss-1)/ss,seen=0;for(unsigned e=0;e<RIXFS_DIRECT_EXTENTS;e++){uint64_t n=in.extent_length[e];if(!n)continue;if(seen>=keep){if(free_inode_data(f,&(rixfs_inode_disk_t){.extent_start={in.extent_start[e]},.extent_length={n}}))return -5;in.extent_start[e]=0;in.extent_length[e]=0;}else if(seen+n>keep){uint64_t cut=seen+n-keep;for(uint64_t j=0;j<cut;j++)if(bit(f,in.extent_start[e]+n-1-j,0))return -6;in.extent_length[e]-=cut;}seen+=n;}in.size=ns;return rixfs_write_inode(f,ino,&in);}
int rixfs_mkdir(rixfs_t *f,uint64_t d,const char *name,uint32_t mode,uint32_t uid,uint32_t gid,uint64_t *out){size_t nl;if(!f||!out||valid_name(name,&nl))return -1;uint64_t old;uint8_t t;if(rixfs_lookup_name(f,d,name,&old,&t)==0)return -2;uint64_t ino;if(alloc_inode(f,&ino))return -3;uint64_t sec;if(alloc_sec(f,&sec))return -4;rixfs_inode_disk_t in={0};in.inode=ino;in.mode=RIXFS_IFDIR|(mode&07777u);in.uid=uid;in.gid=gid;in.generation=1;in.extent_start[0]=sec;in.extent_length[0]=1;if(rixfs_write_inode(f,ino,&in)){bit(f,sec,0);return -5;}rixfs_inode_disk_t dir;if(rixfs_read_inode(f,d,&dir)||append_dirent(f,&dir,ino,RIXFS_DIR_TYPE_DIR,name,nl)){free_inode_data(f,&in);rixfs_inode_disk_t z={0};rixfs_write_inode(f,ino,&z);return -6;}if(rixfs_write_inode(f,d,&dir))return -7;*out=ino;return 0;}
int rixfs_create(rixfs_t *f,uint64_t d,const char *name,uint32_t mode,uint32_t uid,uint32_t gid,uint64_t *out){size_t nl;if(!f||!out||valid_name(name,&nl))return -1;uint64_t old;uint8_t t;if(rixfs_lookup_name(f,d,name,&old,&t)==0)return -2;uint64_t ino;if(alloc_inode(f,&ino))return -3;rixfs_inode_disk_t in={0};in.inode=ino;in.mode=RIXFS_IFREG|(mode&07777u);in.uid=uid;in.gid=gid;in.generation=1;if(rixfs_write_inode(f,ino,&in))return -4;rixfs_inode_disk_t dir;if(rixfs_read_inode(f,d,&dir)||append_dirent(f,&dir,ino,RIXFS_DIR_TYPE_FILE,name,nl)){rixfs_inode_disk_t z={0};rixfs_write_inode(f,ino,&z);return -5;}if(rixfs_write_inode(f,d,&dir))return -6;*out=ino;return 0;}
int rixfs_unlink(rixfs_t *f,uint64_t d,const char *name){size_t nl;if(!f||valid_name(name,&nl))return -1;uint64_t ino;uint8_t type;if(rixfs_lookup_name(f,d,name,&ino,&type))return -2;if(ino==f->super.root_inode)return -3;rixfs_inode_disk_t in;if(rixfs_read_inode(f,ino,&in))return -4;if((in.mode&RIXFS_IFMT)==RIXFS_IFDIR)return -5;if(free_inode_data(f,&in))return -6;rixfs_inode_disk_t z={0};if(rixfs_write_inode(f,ino,&z))return -7;return 0;}
int rixfs_format(rix_block_device_t *d,uint64_t ic){if(!d||d->sector_size<512||d->sector_size>RIXFS_SECTOR_MAX||d->sector_count<128||ic<8)return -1;uint64_t is=(ic*RIXFS_INODE_SIZE+d->sector_size-1)/d->sector_size,bs=(d->sector_count+8*d->sector_size-1)/(8*d->sector_size),js=1+is+bs,ds=js+2;if(ds+1>=d->sector_count)return -2;uint64_t q=pmm_alloc_page();if(!q)return -3;uint8_t *b=(uint8_t*)(uintptr_t)q;for(uint32_t i=0;i<d->sector_size;i++)b[i]=0;rixfs_superblock_t sb={0};sb.magic=RIXFS_MAGIC;sb.version=RIXFS_VERSION;sb.header_size=sizeof(sb);sb.sector_size=d->sector_size;sb.total_sectors=d->sector_count;sb.inode_table_sector=1;sb.inode_count=ic;sb.bitmap_sector=1+is;sb.bitmap_sectors=bs;sb.journal_sector=js;sb.journal_sectors=2;sb.data_start_sector=ds;sb.root_inode=1;sb.generation=1;sb.free_hint=ds;sb.checksum=hash64(&sb,sizeof(sb));for(size_t i=0;i<sizeof(sb);i++)b[i]=((const uint8_t*)&sb)[i];int r=wr(d,0,b);if(r){pmm_free_page(q);return -4;}for(uint64_t s=1;s<ds;s++){for(uint32_t i=0;i<d->sector_size;i++)b[i]=0;if(wr(d,s,b)){pmm_free_page(q);return -5;}}for(uint64_t s=0;s<d->sector_count;s++){uint64_t byte=s/8,bsz=d->sector_size,sec=sb.bitmap_sector+byte/bsz,off=byte%bsz;if(sec>=sb.bitmap_sector+sb.bitmap_sectors)continue;if(s<ds){uint8_t m=(uint8_t)(1u<<(s%8));b[off]|=m;if(off==bsz-1||s+1==ds){if(wr(d,sec,b)){pmm_free_page(q);return -6;}for(uint32_t i=0;i<d->sector_size;i++)b[i]=0;}}}rixfs_t f={.device=d,.super=sb,.mounted=1};uint64_t root;if(alloc_sec(&f,&root)){pmm_free_page(q);return -7;}rixfs_inode_disk_t in={0};in.inode=1;in.mode=RIXFS_IFDIR|0755u;in.generation=1;in.extent_start[0]=root;in.extent_length[0]=1;if(rixfs_write_inode(&f,1,&in)){pmm_free_page(q);return -8;}pmm_free_page(q);return 0;}
