#include "vmm.h"
#include "pmm.h"
#include <stddef.h>
#define TABLE_ENTRIES 512ULL
#define IDENTITY_PD_COUNT 128ULL
#define PAGE_MASK 0x000FFFFFFFFFF000ULL
#define PTE_PS (1ULL<<7)
#define CR0_WP (1ULL<<16)
#define CR4_PAE (1ULL<<5)
#define LEAF_FLAGS (RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE|RIXURI_PTE_USER|RIXURI_PTE_NX|RIXURI_PTE_OWNED)
static uint64_t early_pml4[512] __attribute__((aligned(4096)));static uint64_t early_pdpt[512] __attribute__((aligned(4096)));static uint64_t early_pd[IDENTITY_PD_COUNT][512] __attribute__((aligned(4096)));static uint64_t kernel_pml4_phys;static uint64_t current_pml4_phys;
static inline void write_cr3(uint64_t v){__asm__ volatile("mov %0,%%cr3"::"r"(v):"memory");}static inline void invlpg(uint64_t va){__asm__ volatile("invlpg (%0)"::"r"(va):"memory");}static inline uint64_t read_cr0(void){uint64_t v;__asm__ volatile("mov %%cr0,%0":"=r"(v));return v;}static inline void write_cr0(uint64_t v){__asm__ volatile("mov %0,%%cr0"::"r"(v):"memory");}static inline uint64_t read_cr4(void){uint64_t v;__asm__ volatile("mov %%cr4,%0":"=r"(v));return v;}static inline void write_cr4(uint64_t v){__asm__ volatile("mov %0,%%cr4"::"r"(v):"memory");}
static uint64_t *entry_table(uint64_t e){return(uint64_t *)(uintptr_t)(e&PAGE_MASK);}static int canonical48(uint64_t va){return va<(1ULL<<47)||va>=(UINT64_MAX-(1ULL<<47)+1ULL);}
static uint64_t *ensure_table(uint64_t *parent,size_t index,uint64_t flags){uint64_t e=parent[index];if(e&RIXURI_PTE_PRESENT){if(flags&RIXURI_PTE_USER)parent[index]|=RIXURI_PTE_USER;return entry_table(parent[index]);}uint64_t phys=pmm_alloc_page();if(!phys)return NULL;uint64_t*t=(uint64_t *)(uintptr_t)phys;for(size_t i=0;i<TABLE_ENTRIES;i++)t[i]=0;parent[index]=phys|RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE|(flags&RIXURI_PTE_USER);return t;}
static uint64_t *split_pd_huge_page(uint64_t *pd,size_t index,uint64_t flags){uint64_t e=pd[index];if(!(e&RIXURI_PTE_PRESENT))return ensure_table(pd,index,flags);if(!(e&PTE_PS)){if(flags&RIXURI_PTE_USER)pd[index]|=RIXURI_PTE_USER;return entry_table(pd[index]);}uint64_t phys=pmm_alloc_page();if(!phys)return NULL;uint64_t*pt=(uint64_t *)(uintptr_t)phys;uint64_t base=e&PAGE_MASK;uint64_t leaf=e&(RIXURI_PTE_WRITE|RIXURI_PTE_USER|RIXURI_PTE_NX);for(size_t i=0;i<TABLE_ENTRIES;i++)pt[i]=(base+(uint64_t)i*0x1000ULL)|RIXURI_PTE_PRESENT|leaf;pd[index]=phys|RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE|(e&RIXURI_PTE_USER)|(flags&RIXURI_PTE_USER);return pt;}
void vmm_early_init(void){for(size_t i=0;i<TABLE_ENTRIES;i++){early_pml4[i]=0;early_pdpt[i]=0;}for(size_t n=0;n<IDENTITY_PD_COUNT;n++)for(size_t i=0;i<TABLE_ENTRIES;i++)early_pd[n][i]=0;early_pml4[0]=(uint64_t)(uintptr_t)early_pdpt|RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE;for(uint64_t n=0;n<IDENTITY_PD_COUNT;n++){early_pdpt[n]=(uint64_t)(uintptr_t)early_pd[n]|RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE;for(uint64_t i=0;i<TABLE_ENTRIES;i++){uint64_t pa=(n*TABLE_ENTRIES+i)*0x200000ULL;early_pd[n][i]=pa|RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE|PTE_PS;}}pmm_reserve_page((uint64_t)(uintptr_t)early_pml4);pmm_reserve_page((uint64_t)(uintptr_t)early_pdpt);for(size_t n=0;n<IDENTITY_PD_COUNT;n++)pmm_reserve_page((uint64_t)(uintptr_t)early_pd[n]);kernel_pml4_phys=(uint64_t)(uintptr_t)early_pml4;current_pml4_phys=kernel_pml4_phys;write_cr3(current_pml4_phys);write_cr0(read_cr0()|CR0_WP);write_cr4(read_cr4()|CR4_PAE);}
uint64_t vmm_kernel_pml4(void){return kernel_pml4_phys;}
uint64_t vmm_current_pml4(void){return current_pml4_phys;}
void *vmm_phys_ptr(uint64_t physical_address){if(!physical_address||(physical_address&0xFFFULL)||physical_address>=RIXURI_MAX_PHYS_BYTES)return NULL;return(void *)(uintptr_t)physical_address;}
void vmm_switch_pml4(uint64_t pml4_phys){if(!pml4_phys)return;current_pml4_phys=pml4_phys;write_cr3(pml4_phys);}
int vmm_map_page_in_pml4(uint64_t pml4_phys,uint64_t va,uint64_t pa,uint64_t flags){if(!pml4_phys||!canonical48(va)||(va&0xFFFULL)||(pa&0xFFFULL)||(pa&~PAGE_MASK))return -1;uint64_t*pml4=(uint64_t *)(uintptr_t)pml4_phys;uint64_t*pdpt=ensure_table(pml4,(va>>39)&0x1FFULL,flags);if(!pdpt)return -1;uint64_t*pd=ensure_table(pdpt,(va>>30)&0x1FFULL,flags);if(!pd)return -1;uint64_t*pt=split_pd_huge_page(pd,(va>>21)&0x1FFULL,flags);if(!pt)return -1;size_t idx=(size_t)((va>>12)&0x1FFULL);pt[idx]=(pa&PAGE_MASK)|(flags&LEAF_FLAGS);if(pml4_phys==current_pml4_phys)invlpg(va);return 0;}
int vmm_unmap_page_in_pml4(uint64_t pml4_phys,uint64_t va){if(!pml4_phys||!canonical48(va)||(va&0xFFFULL))return -1;uint64_t*pml4=(uint64_t *)(uintptr_t)pml4_phys;uint64_t e=pml4[(va>>39)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;uint64_t*pdpt=entry_table(e);e=pdpt[(va>>30)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;uint64_t*pd=entry_table(e);e=pd[(va>>21)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT)||(e&PTE_PS))return 0;uint64_t*pt=entry_table(e);pt[(va>>12)&0x1FFULL]=0;if(pml4_phys==current_pml4_phys)invlpg(va);return 0;}
int vmm_map_page(uint64_t va,uint64_t pa,uint64_t flags){return vmm_map_page_in_pml4(current_pml4_phys,va,pa,flags);}
void vmm_unmap_page(uint64_t va){(void)vmm_unmap_page_in_pml4(current_pml4_phys,va);}
uint64_t vmm_translate(uint64_t va){if(!canonical48(va))return 0;uint64_t*pml4=(uint64_t *)(uintptr_t)current_pml4_phys;uint64_t e=pml4[(va>>39)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;uint64_t*pdpt=entry_table(e);e=pdpt[(va>>30)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;uint64_t*pd=entry_table(e);e=pd[(va>>21)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;if(e&PTE_PS)return(e&PAGE_MASK)+(va&0x1FFFFFULL);uint64_t*pt=entry_table(e);e=pt[(va>>12)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;return(e&PAGE_MASK)+(va&0xFFFULL);}
uint64_t vmm_query_flags(uint64_t va){if(!canonical48(va))return 0;uint64_t*pml4=(uint64_t *)(uintptr_t)current_pml4_phys;uint64_t e=pml4[(va>>39)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;uint64_t*pdpt=entry_table(e);e=pdpt[(va>>30)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;uint64_t*pd=entry_table(e);e=pd[(va>>21)&0x1FFULL];if(!(e&RIXURI_PTE_PRESENT))return 0;if(e&PTE_PS)return e&(RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE|RIXURI_PTE_USER|RIXURI_PTE_NX);uint64_t*pt=entry_table(e);e=pt[(va>>12)&0x1FFULL];return e&(RIXURI_PTE_PRESENT|RIXURI_PTE_WRITE|RIXURI_PTE_USER|RIXURI_PTE_NX|RIXURI_PTE_OWNED);}
