#include "acpi.h"
#include <stddef.h>
#include <stdint.h>
#define MAX_TABLE 16
typedef struct __attribute__((packed)) { char sig[8]; uint8_t checksum; char oem[6]; uint8_t revision; uint32_t rsdt; uint32_t length; uint64_t xsdt; uint8_t ext_checksum; uint8_t reserved[3]; } rsdp_t;
typedef struct __attribute__((packed)) { char sig[4]; uint32_t length; uint8_t revision; uint8_t checksum; char oemid[6]; char oemtable[8]; uint32_t oemrev; uint32_t creator; uint32_t creatorrev; } sdt_t;
typedef struct __attribute__((packed)) { uint8_t type; uint8_t length; } madt_hdr_t;
typedef struct __attribute__((packed)) { sdt_t h; uint32_t lapic; uint32_t flags; } madt_t;
typedef struct __attribute__((packed)) { uint8_t type, length, acpi_id, apic_id; uint32_t flags; } madt_lapic_t;
typedef struct __attribute__((packed)) { uint8_t type, length, id, reserved; uint32_t address, gsi_base; } madt_ioapic_t;
typedef struct __attribute__((packed)) { uint8_t type, length, bus, source; uint32_t gsi; uint16_t flags; } madt_iso_t;
typedef struct __attribute__((packed)) { uint8_t type, length; uint16_t reserved; uint32_t x2apic_id, flags, acpi_uid; } madt_x2apic_t;
typedef struct __attribute__((packed)) { uint64_t base; uint16_t segment; uint8_t start_bus; uint8_t end_bus; uint32_t reserved; } mcfg_entry_t;
typedef struct __attribute__((packed)) { char sig[4]; uint32_t length; uint8_t revision; uint8_t checksum; char rest[4]; } generic_sdt_t;
static acpi_cpu_info_t cpus[ACPI_MAX_CPUS]; static acpi_ioapic_info_t ioapics[ACPI_MAX_IOAPICS]; static acpi_mcfg_info_t mcfgs[ACPI_MAX_MCFG];
static size_t cpu_n,ioapic_n,mcfg_n; static struct { uint8_t source; uint32_t gsi; uint16_t flags; } iso[16]; static size_t iso_n; static acpi_power_info_t power;
static uint8_t sum8(const void*p,size_t n){const uint8_t*b=p;uint8_t s=0;while(n--)s=(uint8_t)(s+*b++);return s;}
static int sig4(const sdt_t*t,const char*s){return t&&t->sig[0]==s[0]&&t->sig[1]==s[1]&&t->sig[2]==s[2]&&t->sig[3]==s[3];}
static sdt_t*find_table(const rsdp_t*r,const char*sig){if(r->revision>=2&&r->xsdt){sdt_t*x=(sdt_t*)(uintptr_t)r->xsdt;if(x->length>=sizeof(sdt_t)&&x->length<=65536&&sum8(x,x->length)==0){size_t n=(x->length-sizeof(sdt_t))/8;uint64_t*e=(uint64_t*)((uint8_t*)x+sizeof(sdt_t));for(size_t i=0;i<n&&i<MAX_TABLE;i++){sdt_t*t=(sdt_t*)(uintptr_t)e[i];if(t&&sig4(t,sig)&&t->length>=sizeof(sdt_t)&&t->length<=65536&&sum8(t,t->length)==0)return t;}}}if(r->rsdt){sdt_t*x=(sdt_t*)(uintptr_t)(uint64_t)r->rsdt;if(x->length>=sizeof(sdt_t)&&x->length<=65536&&sum8(x,x->length)==0){size_t n=(x->length-sizeof(sdt_t))/4;uint32_t*e=(uint32_t*)((uint8_t*)x+sizeof(sdt_t));for(size_t i=0;i<n&&i<MAX_TABLE;i++){sdt_t*t=(sdt_t*)(uintptr_t)(uint64_t)e[i];if(t&&sig4(t,sig)&&t->length>=sizeof(sdt_t)&&t->length<=65536&&sum8(t,t->length)==0)return t;}}}return NULL;}
static int aml_integer(const uint8_t*p,size_t n,uint16_t*out,size_t*used){if(!p||!out||!used||!n)return-1;switch(p[0]){case 0x00:*out=0;*used=1;return 0;case 0x01:*out=1;*used=1;return 0;case 0x0A:if(n<2)return-1;*out=p[1];*used=2;return 0;case 0x0B:if(n<3)return-1;*out=(uint16_t)p[1]|((uint16_t)p[2]<<8);*used=3;return 0;default:return-1;}}
static int parse_s5(const uint8_t*d,size_t n,uint16_t*a,uint16_t*b){if(!d||!a||!b)return-1;for(size_t i=0;i+7<n;i++){if(d[i]!='_'||d[i+1]!='S'||d[i+2]!='5'||d[i+3]!='_')continue;size_t p=i+4;if(p>=n||d[p++]!=0x12||p>=n)continue;uint8_t pkg=d[p++];size_t payload=(size_t)(pkg&0x0Fu);if(payload<2||p+payload>n)continue;uint8_t count=d[p++];if(count<2)continue;size_t u,v;uint16_t x,y;if(aml_integer(d+p,payload-1,&x,&u)||aml_integer(d+p+u,payload-1-u,&y,&v))continue;*a=x;*b=y;return 0;}return-1;}
static void parse_power(const rsdp_t*r){power=(acpi_power_info_t){0};sdt_t*t=find_table(r,"FACP");if(!t||t->length<116)return;uint8_t*b=(uint8_t*)t;uint32_t dsdt=(uint32_t)b[40]|((uint32_t)b[41]<<8)|((uint32_t)b[42]<<16)|((uint32_t)b[43]<<24);uint32_t pm1a=(uint32_t)b[64]|((uint32_t)b[65]<<8)|((uint32_t)b[66]<<16)|((uint32_t)b[67]<<24);uint32_t pm1b=(uint32_t)b[68]|((uint32_t)b[69]<<8)|((uint32_t)b[70]<<16)|((uint32_t)b[71]<<24);uint64_t xdsdt=0;if(t->length>=148)for(unsigned i=0;i<8;i++)xdsdt|=(uint64_t)b[140+i]<<(8*i);sdt_t*d=xdsdt?(sdt_t*)(uintptr_t)xdsdt:(sdt_t*)(uintptr_t)(uint64_t)dsdt;if(!d||d->length<sizeof(sdt_t)||d->length>1048576||sum8(d,d->length)!=0)return;uint16_t sa,sb;if(pm1a&&parse_s5((uint8_t*)d,d->length,&sa,&sb)==0){power.pm1a_control=(uint16_t)pm1a;power.pm1b_control=(uint16_t)pm1b;power.sleep_type_a=(uint16_t)(sa<<10);power.sleep_type_b=(uint16_t)(sb<<10);power.available=1;}}
int acpi_init(uint64_t rsdp_phys){cpu_n=ioapic_n=mcfg_n=iso_n=0;power=(acpi_power_info_t){0};if(!rsdp_phys)return-1;rsdp_t*r=(rsdp_t*)(uintptr_t)rsdp_phys;if(r->sig[0]!='R'||r->sig[1]!='S'||r->sig[2]!='D'||r->sig[3]!=' '||r->sig[4]!='P'||r->sig[5]!='T'||r->sig[6]!='R'||r->sig[7]!=' ')return-1;size_t len=20;if(r->revision>=2){if(r->length<sizeof(rsdp_t)||r->length>4096)return-1;len=r->length;}if(sum8(r,len)!=0)return-1;sdt_t*t=find_table(r,"APIC");if(!t||t->length<sizeof(madt_t)||sum8(t,t->length)!=0)return-1;madt_t*m=(madt_t*)t;uint8_t*p=(uint8_t*)m+sizeof(madt_t),*end=(uint8_t*)m+m->h.length;while(p+2<=end){madt_hdr_t*h=(madt_hdr_t*)p;if(h->length<2||p+h->length>end)return-2;if(h->type==0&&h->length>=sizeof(madt_lapic_t)&&cpu_n<ACPI_MAX_CPUS){madt_lapic_t*x=(madt_lapic_t*)p;cpus[cpu_n++]=(acpi_cpu_info_t){x->acpi_id,(uint8_t)(x->flags&1),0,x->apic_id};}else if(h->type==1&&h->length>=sizeof(madt_ioapic_t)&&ioapic_n<ACPI_MAX_IOAPICS){madt_ioapic_t*x=(madt_ioapic_t*)p;ioapics[ioapic_n++]=(acpi_ioapic_info_t){x->id,x->address,x->gsi_base};}else if(h->type==2&&h->length>=sizeof(madt_iso_t)&&iso_n<16){madt_iso_t*x=(madt_iso_t*)p;iso[iso_n].source=x->source;iso[iso_n].gsi=x->gsi;iso[iso_n++].flags=x->flags;}else if(h->type==9&&h->length>=sizeof(madt_x2apic_t)&&cpu_n<ACPI_MAX_CPUS){madt_x2apic_t*x=(madt_x2apic_t*)p;cpus[cpu_n++]=(acpi_cpu_info_t){0,(uint8_t)(x->flags&1),1,x->x2apic_id};}p+=h->length;}sdt_t*mcfg=find_table(r,"MCFG");if(mcfg&&mcfg->length>=sizeof(generic_sdt_t)+8){size_t n=(mcfg->length-sizeof(generic_sdt_t))/sizeof(mcfg_entry_t);mcfg_entry_t*e=(mcfg_entry_t*)((uint8_t*)mcfg+sizeof(generic_sdt_t));for(size_t i=0;i<n&&mcfg_n<ACPI_MAX_MCFG;i++)if(e[i].end_bus>=e[i].start_bus&&e[i].base)mcfgs[mcfg_n++]=(acpi_mcfg_info_t){e[i].base,e[i].segment,e[i].start_bus,e[i].end_bus};}parse_power(r);return 0;}
size_t acpi_cpu_count(void){return cpu_n;}size_t acpi_ioapic_count(void){return ioapic_n;}size_t acpi_mcfg_count(void){return mcfg_n;}
const acpi_cpu_info_t*acpi_cpu(size_t i){return i<cpu_n?&cpus[i]:NULL;}const acpi_ioapic_info_t*acpi_ioapic(size_t i){return i<ioapic_n?&ioapics[i]:NULL;}const acpi_mcfg_info_t*acpi_mcfg(size_t i){return i<mcfg_n?&mcfgs[i]:NULL;}
uint32_t acpi_irq_gsi(uint8_t irq,uint16_t*flags){for(size_t i=0;i<iso_n;i++)if(iso[i].source==irq){if(flags)*flags=iso[i].flags;return iso[i].gsi;}if(flags)*flags=0;return irq;}
int acpi_power_info(acpi_power_info_t*out){if(!out)return-1;*out=power;return power.available?0:-2;}
