#include "pci.h"
#include "../arch/x86_64/acpi.h"
#include <stddef.h>
#include <stdint.h>
static rix_pci_device_t devices[RIX_PCI_MAX_DEVICES];static size_t count;
static inline void outl(uint16_t p,uint32_t v){__asm__ volatile("outl %0,%1"::"a"(v),"Nd"(p));}static inline uint32_t inl(uint16_t p){uint32_t v;__asm__ volatile("inl %1,%0":"=a"(v):"Nd"(p));return v;}
uint32_t pci_config_read32(uint8_t b,uint8_t d,uint8_t f,uint8_t o){if(d>=32||f>=8||(o&3)||o>=256)return 0xffffffffu;outl(0xCF8,0x80000000u|((uint32_t)b<<16)|((uint32_t)d<<11)|((uint32_t)f<<8)|o);return inl(0xCFC);}
int pci_config_write32(uint8_t b,uint8_t d,uint8_t f,uint8_t o,uint32_t v){if(d>=32||f>=8||(o&3)||o>=256)return -1;outl(0xCF8,0x80000000u|((uint32_t)b<<16)|((uint32_t)d<<11)|((uint32_t)f<<8)|o);outl(0xCFC,v);return 0;}
static volatile uint32_t*ecam_ptr(uint16_t s,uint8_t b,uint8_t d,uint8_t f,uint8_t o){for(size_t i=0;i<acpi_mcfg_count();i++){const acpi_mcfg_info_t*m=acpi_mcfg(i);if(m->segment!=s||b<m->start_bus||b>m->end_bus)continue;uint64_t a=m->base+((uint64_t)(b-m->start_bus)<<20)+((uint64_t)d<<15)+((uint64_t)f<<12)+o;return(volatile uint32_t*)(uintptr_t)a;}return NULL;}
uint32_t pci_config_read32_ecam(uint16_t s,uint8_t b,uint8_t d,uint8_t f,uint8_t o){if(d>=32||f>=8||(o&3)||o>=4096)return 0xffffffffu;volatile uint32_t*p=ecam_ptr(s,b,d,f,o);return p?*p:0xffffffffu;}int pci_config_write32_ecam(uint16_t s,uint8_t b,uint8_t d,uint8_t f,uint8_t o,uint32_t v){if(d>=32||f>=8||(o&3)||o>=4096)return -1;volatile uint32_t*p=ecam_ptr(s,b,d,f,o);if(!p)return -1;*p=v;return 0;}
static void scan_function(uint8_t b,uint8_t d,uint8_t f){if(count>=RIX_PCI_MAX_DEVICES)return;uint32_t id=pci_config_read32(b,d,f,0);if(id==0xffffffffu)return;rix_pci_device_t*x=&devices[count++];x->bus=b;x->device=d;x->function=f;x->vendor_id=(uint16_t)id;x->device_id=(uint16_t)(id>>16);uint32_t c=pci_config_read32(b,d,f,8);x->revision=(uint8_t)c;x->prog_if=(uint8_t)(c>>8);x->subclass=(uint8_t)(c>>16);x->class_code=(uint8_t)(c>>24);x->header_type=(uint8_t)(pci_config_read32(b,d,f,0xC)>>16);for(unsigned i=0;i<6;i++)x->bars[i]=pci_config_read32(b,d,f,(uint8_t)(0x10+i*4));}
int pci_find_capability(const rix_pci_device_t*d,uint8_t cap,uint8_t*off){if(!d||!off)return -1;uint16_t status=(uint16_t)(pci_config_read32(d->bus,d->device,d->function,4)>>16);if(!(status&0x10))return -1;uint8_t p=(uint8_t)(pci_config_read32(d->bus,d->device,d->function,0x34)&255);for(unsigned n=0;p&&n<48;n++){if(p<0x40||p>=0x100||(p&3))return -1;uint32_t h=pci_config_read32(d->bus,d->device,d->function,p);if((uint8_t)h==cap){*off=p;return 0;}p=(uint8_t)(h>>8);}return -1;}
int pci_bar_size(const rix_pci_device_t*d,unsigned bar,uint64_t*size,uint64_t*base,int*is_io){if(!d||!size||!base||!is_io||bar>=6||d->header_type&0x7f)return -1;uint8_t o=(uint8_t)(0x10+bar*4);uint32_t orig=pci_config_read32(d->bus,d->device,d->function,o);if(orig==0xffffffffu)return -1;*is_io=(int)(orig&1u);if(*is_io){pci_config_write32(d->bus,d->device,d->function,o,0xffffffffu);uint32_t mask=pci_config_read32(d->bus,d->device,d->function,o);pci_config_write32(d->bus,d->device,d->function,o,orig);uint32_t m=mask&~3u;if(!m)return -1;*base=orig&~3u;*size=(uint64_t)(~m+1u);return 0;}unsigned type=(orig>>1)&3u;if(type==2){if(bar==5)return -1;uint32_t hi=pci_config_read32(d->bus,d->device,d->function,(uint8_t)(o+4));pci_config_write32(d->bus,d->device,d->function,o,0xffffffffu);pci_config_write32(d->bus,d->device,d->function,(uint8_t)(o+4),0xffffffffu);uint32_t lo_mask=pci_config_read32(d->bus,d->device,d->function,o),hi_mask=pci_config_read32(d->bus,d->device,d->function,(uint8_t)(o+4));pci_config_write32(d->bus,d->device,d->function,o,orig);pci_config_write32(d->bus,d->device,d->function,(uint8_t)(o+4),hi);uint64_t mask=((uint64_t)hi_mask<<32)|(lo_mask&~0xfu);if(!mask)return -1;*base=((uint64_t)hi<<32)|(orig&~0xfu);*size=(~mask)+1ULL;return 0;}uint32_t m;*base=orig&~0xfu;pci_config_write32(d->bus,d->device,d->function,o,0xffffffffu);m=pci_config_read32(d->bus,d->device,d->function,o);pci_config_write32(d->bus,d->device,d->function,o,orig);m&=~0xfu;if(!m)return -1;*size=(uint64_t)(~m+1u);return 0;}
int pci_msix_info(const rix_pci_device_t*d,uint16_t*n,uint8_t*bir,uint32_t*off){if(!d||!n||!bir||!off)return -1;uint8_t p;if(pci_find_capability(d,0x11,&p)!=0)return -1;uint32_t c=pci_config_read32(d->bus,d->device,d->function,p);*n=(uint16_t)((c>>16)&0x7ffu)+1u;uint32_t t=pci_config_read32(d->bus,d->device,d->function,(uint8_t)(p+4));*bir=(uint8_t)(t&7u);*off=t&0xfffffff8u;return 0;}
int pci_init(void){count=0;for(unsigned b=0;b<256&&count<RIX_PCI_MAX_DEVICES;b++)for(unsigned d=0;d<32&&count<RIX_PCI_MAX_DEVICES;d++){uint32_t id=pci_config_read32((uint8_t)b,(uint8_t)d,0,0);if(id==0xffffffffu)continue;scan_function((uint8_t)b,(uint8_t)d,0);uint8_t h=(uint8_t)(pci_config_read32((uint8_t)b,(uint8_t)d,0,0xC)>>16);if(h&0x80)for(uint8_t f=1;f<8&&count<RIX_PCI_MAX_DEVICES;f++)scan_function((uint8_t)b,(uint8_t)d,f);}return 0;}
size_t pci_device_count(void){return count;}const rix_pci_device_t*pci_device(size_t i){return i<count?&devices[i]:NULL;}
