#include "process.h"
#include "../elf/loader.h"
#include "../mm/pmm.h"
#include "../mm/vmm.h"
#include "../arch/x86_64/tss.h"
#include "../vfs/vfs.h"
#include <stddef.h>
#define USER_STACK_TOP 0x00007FFFFFFFF000ULL
#define USER_STACK_PAGES 8ULL
#define USER_STACK_BASE (USER_STACK_TOP-USER_STACK_PAGES*4096ULL)
#define KERNEL_STACK_SIZE 4096ULL
static rix_process_t table[RIX_PROCESS_MAX];static pid_t current_pid;static pid_t next_pid;static size_t live_count;
static size_t bounded_strlen(const char*s){size_t n=0;if(!s)return 0;while(n<RIX_PROCESS_NAME_MAX-1&&s[n])n++;return n;}
static void copy_name(char*d,const char*s){size_t n=bounded_strlen(s);for(size_t i=0;i<n;i++)d[i]=s[i];d[n]=0;}
static void clear_process(rix_process_t*p){p->pid=0;p->parent=0;p->process_group=0;p->session=0;p->state=RIX_PROC_UNUSED;p->uid=0;p->gid=0;p->address_space.pml4_phys=0;p->kernel_stack=0;p->kernel_stack_size=0;p->exit_status=0;p->fd_bitmap=0;p->signal_pending=0;p->signal_mask=0;p->name[0]=0;}
static void zero_page(uint64_t pa){uint8_t*p=(uint8_t*)(uintptr_t)pa;for(size_t i=0;i<4096;i++)p[i]=0;}
int process_init(void){for(size_t i=0;i<RIX_PROCESS_MAX;i++)clear_process(&table[i]);current_pid=0;next_pid=1;live_count=1;table[0].pid=0;table[0].process_group=0;table[0].session=0;table[0].state=RIX_PROC_RUNNING;copy_name(table[0].name,"kernel");return 0;}
pid_t process_current(void){return current_pid;}rix_process_t*process_lookup(pid_t pid){for(size_t i=0;i<RIX_PROCESS_MAX;i++)if(table[i].state!=RIX_PROC_UNUSED&&table[i].pid==pid)return &table[i];return NULL;}size_t process_count(void){return live_count;}
int process_create(const char*name,pid_t parent,pid_t*out_pid){if(!name||!name[0]||(parent&& !process_lookup(parent)))return -1;for(size_t i=1;i<RIX_PROCESS_MAX;i++)if(table[i].state==RIX_PROC_UNUSED){pid_t pid=next_pid++;if(!pid)pid=next_pid++;clear_process(&table[i]);table[i].pid=pid;table[i].parent=parent;rix_process_t*pp=parent?process_lookup(parent):NULL;table[i].process_group=pp?pp->process_group:pid;table[i].session=pp?pp->session:pid;table[i].state=RIX_PROC_SLEEPING;if(parent&&vfs_clone_fds(parent,pid)!=0){clear_process(&table[i]);return -1;}copy_name(table[i].name,name);live_count++;if(out_pid)*out_pid=pid;return 0;}return -1;}
int process_create_user(const char*name,pid_t parent,const void*image,uint64_t image_size,pid_t*out_pid,uint64_t*out_entry,uint64_t*out_user_stack){if(!name||!name[0]||!image||!image_size||!out_pid||!out_entry||!out_user_stack||(parent&&!process_lookup(parent)))return -1;pid_t pid;if(process_create(name,parent,&pid)!=0)return -1;rix_process_t*p=process_lookup(pid);if(!p)return -1;if(address_space_create(&p->address_space)!=0)goto fail;for(uint64_t i=0;i<USER_STACK_PAGES;i++){uint64_t pa=pmm_alloc_page();if(!pa)goto fail;zero_page(pa);if(address_space_map(&p->address_space,USER_STACK_BASE+i*4096ULL,pa,RIXURI_PTE_WRITE|RIXURI_PTE_USER|RIXURI_PTE_NX)!=0){pmm_free_page(pa);goto fail;}}rix_elf_image_t elf;if(elf_load_image(image,image_size,&p->address_space,&elf)!=0)goto fail;uint64_t ks=pmm_alloc_page();if(!ks)goto fail;zero_page(ks);p->kernel_stack=ks;p->kernel_stack_size=KERNEL_STACK_SIZE;p->state=RIX_PROC_SLEEPING;*out_pid=pid;*out_entry=elf.entry;*out_user_stack=USER_STACK_TOP;return 0;fail:(void)vfs_close_all(pid);address_space_destroy(&p->address_space);if(p->kernel_stack)pmm_free_page(p->kernel_stack);clear_process(p);if(live_count)live_count--;return -1;}
int process_activate(pid_t pid){if(pid==0){current_pid=0;uint64_t cr3=vmm_kernel_pml4();__asm__ volatile("mov %0,%%cr3"::"r"(cr3):"memory");return 0;}rix_process_t*p=process_lookup(pid);if(!p||p->state==RIX_PROC_UNUSED||p->state==RIX_PROC_ZOMBIE||!p->address_space.pml4_phys||!p->kernel_stack)return -1;current_pid=pid;tss_set_rsp0(p->kernel_stack+p->kernel_stack_size);__asm__ volatile("mov %0,%%cr3"::"r"(p->address_space.pml4_phys):"memory");return 0;}
int process_set_state(pid_t pid,rix_process_state_t state){rix_process_t*p=process_lookup(pid);if(!p||state==RIX_PROC_UNUSED)return -1;rix_process_state_t old=p->state;p->state=state;if(state==RIX_PROC_RUNNING&&process_activate(pid)!=0){p->state=old;return -1;}return 0;}
int process_exit(pid_t pid,uint64_t status){rix_process_t*p=process_lookup(pid);if(!p||pid==0)return -1;p->exit_status=status;p->state=RIX_PROC_ZOMBIE;if(current_pid==pid)current_pid=0;return 0;}
int process_set_group(pid_t pid,pid_t process_group){rix_process_t*p=process_lookup(pid);if(!p||!process_group)return -1;p->process_group=process_group;return 0;}
int process_set_session(pid_t pid,pid_t session){rix_process_t*p=process_lookup(pid);if(!p||!session)return -1;p->session=session;return 0;}
int process_signal_group(pid_t process_group,unsigned signal){if(!process_group||signal<1u||signal>64u)return -1;uint64_t bit=1ULL<<(signal-1u);int sent=0;for(size_t i=0;i<RIX_PROCESS_MAX;i++){rix_process_t*p=&table[i];if(p->state!=RIX_PROC_UNUSED&&p->state!=RIX_PROC_ZOMBIE&&p->process_group==process_group){p->signal_pending|=bit;if(p->state==RIX_PROC_SLEEPING&&(p->signal_mask&bit)==0)p->state=RIX_PROC_RUNNING;sent++;}}return sent?0:-1;}
int process_wait(pid_t parent,pid_t wanted,uint64_t*status,pid_t*child_pid){if(!status||!child_pid)return -1;rix_process_t*match=NULL;for(size_t i=1;i<RIX_PROCESS_MAX;i++){rix_process_t*p=&table[i];if(p->state==RIX_PROC_ZOMBIE&&p->parent==parent&&(wanted==(pid_t)-1||p->pid==wanted)){match=p;break;}}if(!match)return 1;*status=match->exit_status;*child_pid=match->pid;(void)vfs_close_all(match->pid);address_space_destroy(&match->address_space);if(match->kernel_stack)pmm_free_page(match->kernel_stack);clear_process(match);if(live_count)live_count--;return 0;}
